---
- name: 'Ensure FirewallD is installed'
  ansible.builtin.package:
    name: 'firewalld'
    state: 'present'

- name: 'Ensure FirewallD is running'
  ansible.builtin.service:
    name: 'firewalld'
    state: 'started'

- name: 'Manage zones'
  ansible.builtin.include_tasks: 'tasks/manage_zone.yml'
  loop: "{{ firewalld_zones }}"
  loop_control:
    loop_var: 'zone'

- name: 'Remove unknown ports and serices'
  when: firewalld_prune_unknown
  block:
    - name: 'Collect current FirewallD configuration'
      ansible.posix.firewalld_info:
        active_zones: true
      register: 'firewalld_config'

    - name: 'Prune zones'
      ansible.builtin.include_tasks: 'tasks/prune_zone.yml'
      loop: "{{ firewalld_zones }}"
      loop_control:
        loop_var: 'zone'
