---
- name: "{{ zone }} - Remove all unknown services from zone"  # noqa name[template]
  ansible.posix.firewalld:
    service: "{{ service }}"
    zone: "{{ zone }}"
    state: 'disabled'
    immediate: true
    permanent: true
  when:
    - service not in firewalld_zones[zone]['services']
  loop: "{{ firewalld_config['firewalld_info']['zones'][zone]['services'] }}"
  loop_control:
    loop_var: 'service'

- name: "{{ zone }} - Remove all unknown ports from zone"  # noqa name[template]
  ansible.posix.firewalld:
    port: "{{ port[0] }}/{{ port[1] }}"  # For some reason the info module reports these weird
    zone: "{{ zone }}"
    state: 'disabled'
    immediate: true
    permanent: true
  when: port[0] + '/' + port[1] not in firewalld_zones[zone]['ports']
  loop: "{{ firewalld_config['firewalld_info']['zones'][zone]['ports'] }}"
  loop_control:
    loop_var: 'port'

- name: "{{ zone }} - Remove all unknown rich rules from zone"  # noqa name[template]
  ansible.posix.firewalld:
    rich_rule: "{{ rule }}"
    zone: "{{ zone }}"
    state: 'disabled'
    immediate: true
    permanent: true
  when: rule not in firewalld_zones[zone]['rich_rules']
  loop: "{{ firewalld_config['firewalld_info']['zones'][zone]['rich_rules'] }}"
  loop_control:
    loop_var: 'rule'

- name: "{{ zone }} - Remove all protocols from zone"  # noqa name[template]
  ansible.posix.firewalld:
    protocol: "{{ protocol }}"
    zone: "{{ zone }}"
    state: 'disabled'
    immediate: true
    permanent: true
  loop: "{{ firewalld_config['firewalld_info']['zones'][zone]['protocols'] }}"
  loop_control:
    loop_var: 'protocol'

- name: "{{ zone }} - Remove all unknown sources from zone"  # noqa name[template]
  ansible.posix.firewalld:
    source: "{{ source }}"
    zone: "{{ zone }}"
    state: 'disabled'
    immediate: true
    permanent: true
  when: source not in firewalld_zones[zone]['sources']
  loop: "{{ firewalld_config['firewalld_info']['zones'][zone]['sources'] }}"
  loop_control:
    loop_var: 'source'
