---
# yamllint disable rule:line-length
- name: 'Converge'
  hosts: 'all'
  vars:
    # Please note that the config below makes no sense at all, it's just used to test the role's functions
    global_firewalld_zones__to_merge:
      public:
        target: 'DROP'
        services:
          - 'ssh'
          - 'http'
        ports:
          - '10050/tcp'
        sources:
          - '10.0.0.0/8'
    dhcpd_firewalld_zones__to_merge:
      public:
        services:
          - 'dhcp'
        sources:
          - '11.0.0.0/8'
    extra_zone_firewalld_zones__to_merge:
      management:
        target: 'ACCEPT'
        services:
          - 'https'
        sources:
          - '192.168.1.0/24'
          - '192.168.2.0/24'
        rich_rules:
          - 'rule family="ipv4" forward-port port="80" protocol="tcp" to-port="8080" to-addr="192.168.3.12"'
    firewalld_zones: "{{ lookup('community.general.merge_variables', '_firewalld_zones__to_merge', pattern_type='suffix') | dict2items(key_name='zone', value_name='config') }}"
  tasks:
    - name: 'Run role'
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
